### PR TITLE
Update strongbolt.gemspec

### PR DESCRIPTION
**Pull request by onkeld**
Just updated the version of simple_form in the Gemspec for now.
I'm not able to test this right now, will possibly get to some testing during the weekend.
I am not sure this is enough to resolve Issue #45 - will report back wether this breaks anything after some testing...

### CODE REVIEW

**Comment by onkeld** [comment]
OK, first tests indicate everything is ok with this change.
Running Rspec on the code throws a couple of deprecation warnings and one single failure which has nothing to do with simple_form.
If I however change the rails dependency to 5.2 as well, none of the trsts pass as there is already a missing method error with rails configuration.
There seems to be some change with the asset pipeline causing a problem there.

**Comment by onkeld** [comment]
If we depend on Rails 5.2, we need to activate Sprockets railitie in order to be able to run any specs.
Once that is done, the majority of specs seem to fail however.
I am not that deep in strongbolt yet to figure out what causes the specs to fail. 
Anybody got any good ideas as to what is happening here?

**Comment by tobithiel** [comment]
@onkeld Could you share (some of) the errors here?

**Comment by onkeld** [comment]
On a quick glance, some of the errors are due to missing dependencies in rails 5 apparently (I'm reminded to install certain gems). 
Lots of times I get missing attributes errors for id columns. Could it be that fabricatiing entries in the testing database doesn't work properly anymore in Rails 5?
If I get time I will try to work through the list.

The attached file contains the full rspec output.
[rspec-output.txt](https://github.com/605data/strongbolt/files/2265202/rspec-output.txt)

**Comment by tobithiel** [comment]
@onkeld I would try keeping `rspec` at the old version for now? It seems to me as if some of the testing helpers changed.

**Comment by matissg** [comment]
@tobithiel  @onkeld Any news regarding this pull request?

**Comment by onkeld** [comment]
@tobithiel Which rspec version have you been running?
I tried the 3.5 and 3.8 versions so far, both throw lots of errors...
@matissg By my tests, simply changing the dependency for simple_form to a new version seems to be enough to get things compatible - however, the update of Rails seems to break most rspec specs - still trying to figure out what's going on there...

**Comment by onkeld** [comment]
Anything below rspec 3.5.0 will not be compatible with rails 5.2 - rspec-rails 3.4.0 depends on actionpack <4.3, so is incompatible with rails 5.
With rspec-rails above v3.5.0 we get the errors I posted in the text file from your tests.
Looks like we'll have to repair all the tests to get them running on the new version of rspec before we can pull this change off...

**Comment by tobithiel** [comment]
3.5 was the old rspec version, I guess it must be something else then. Not sure what right now.
The newer `simple_form` version is not compatible with the Rails 4.2 versions anymore?

**Comment by onkeld** [comment]
Apparently not - the new gemspec for simple_form requires activemodel and actionpack in versions >=5.0

**Comment by tobithiel** [comment]
@onkeld If you rewrite [this line](https://github.com/605data/strongbolt/blob/master/spec/controllers/strongbolt/capabilities_controller_spec.rb#L86) from `let(:create) { post :create, capability: attributes, role_id: role.id, format: :json }` to `let(:create) { post :create, params: { capability: attributes, role_id: role.id }, format: :json }` it works again.
We need to maintain a Rails 4.2 compatible version, but this seems to break under Rails 4.2 unfortunately. I'm not sure how to write it, so it can be compatible with both versions.

**Comment by onkeld** [comment]
Seems to be related to the new way of handling strong parameters or something...
I'll have a look wether it is possible to write some sort of selector (if Rails 4.2 use this test, if rails 5.2, use the other or something like that...)

**Comment by onkeld** [comment]
After looking at it for a bit longer, I expect the strong parameters to be the main problem.
The new way of securing parameters was introduced in rails 4, so I'm not quite sure why this error didn't pop up earlier.
I'm still testing, but my first thoughts are that the parameter role_id is not among the permitted parameters in the capabilities controller.
Will report back once I find out how to fix...

**Comment by onkeld** [comment]
Actually, all my ideas so far have been wrong - it all comes down to a change in the Rails Api with version 5 - apparently HTTP request methods will accept only the following keyword arguments params, headers, env, xhr, format in the new rails version...

For now, I found a rather simple solution which requires a lot of busywork though...
A simple if-clause in the tests does the trick:
```ruby
  if Rails.version <= '5.0.0'
    let(:create) { post :create, capability: attributes, role_id: role.id }
  else 
    let(:create) { post :create, params: {capability: attributes, role_id: role.id }}
  end
```
This has to be done for each instance of the problem popping up.
If anybody has a suggestion on how to make this simpler, I'd be very happy!

**Comment by matissg** [comment]
@onkeld @tobithiel Do you think there is any solution to have the gem working for Rails 5.2.?

**Comment by onkeld** [comment]
@matissg I have started to add above if-clause to all the tests that need it as I don't really want to mess with HTTP-requests. 
It's a rather tedious and repetitive task and since this project is only a hobby project and my holidays are over it might take some time...

Another option could be a change in the way test data is generated. I haven't tested this, but I would expect abstracting the test data layer from the rails version could help... Ever thought about using [FactoryBot](https://github.com/thoughtbot/factory_bot) for generating test data?
I would suspect that a Factory would know how to actually set the parameters correctly based on rails versions as long as the rails version is supported by factoryBot...
Would be just as tedious to rework all the tests though... ;-)

I suspect I might make some more progress here soon - keep you posted.

**Comment by tobithiel** [comment]
@onkeld @matissg I pushed a few commits that deal with the Rails 5 compatibility. The unit tests pass now, but I'd encourage you guys to check if things still work fine otherwise as well.

**Comment by matissg** [comment]
@tobithiel  I could check if it works for Rails 5.2 How can I get it? Doesn't seemed to be on master branch.

**Comment by tobithiel** [comment]
@matissg I added them to this PR.

**Comment by tobithiel** [comment]
Feel free to reopen if you're still interested

**Comment by kinsomicrote** [comment]
This depends on version 3.1 of simpleform which depends on version >= 4.0.0, < 4.1 of actionpack.

```
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    rails (~> 5.2.2) was resolved to 5.2.2, which depends on
      actionpack (= 5.2.2)

    strongbolt (~> 0.3.16) was resolved to 0.3.16, which depends on
      simple_form (~> 3.0) was resolved to 3.0.1, which depends on
        actionpack (>= 4.0.0, < 4.1)
```

**Comment by tobithiel** [comment]
@kinsomicrote That's what this PR is trying to fix, but it never got finished. If you're interested, we'd appreciate your help in testing this.

**Pull request closed without merging**
